# created by Muhammad Acla (github: https://github.com/aclaputra)
version: '3'
services:
  payara:
    image: 'payara/server-full'
    command: sh -c "/opt/payara/appserver/bin/asadmin --user admin --passwordfile /opt/payara/passwordFile" 
    command: sh -c "start-domain ${PAYARA_DOMAIN}"
    command: sh -c "deploy /opt/payara/deployments/twitter.war"
    build: payara
    ports:
      - 4848:4848
      - 8080:8080
      - 8181:8181
    volumes:
      - ./logs:/opt/payara/appserver/glassfish/domains/payaradomain/logs
      - ./build/libs:/opt/payara/deployments
    working_dir: /opt/payara/deployments
    environment:
      - PAYARA_DOMAIN=payaradomain
