# created by Muhammad Acla (github: https://github.com/aclaputra)
version: '3'
services:
  payara:
    image: 'payara/server-full'
    command: sh -c "/opt/payara/appserver/bin/asadmin"
    command: sh -c "admin"
    command: sh -c "admin"
    command: sh -c "deploy /opt/lampp/htdocs/twitter-app/build/libs/twitter.war"
    build: payara
    ports:
      - 4848:4848
      - 8080:8080
      - 8181:8181
    volumes:
      - ./deployments:/opt/payara/deployments
      - ./logs:/opt/payara/appserver/glassfish/domains/payaradomain/logs
      - ./vvvConfiguration:/opt/vdz/config
    working_dir: /opt/payara/deployments
    environment:
      - PAYARA_DOMAIN=payaradomain
