# created by Muhammad Acla (github: https://github.com/aclaputra)
version: '3'
services:
  payara:
    image: 'payara/server-full'
    command: sh -c "${AS_ADMIN_PATH} --user ${USER} --passwordfile ${PASSWORDFILE_PATH}" 
    command: sh -c "start-domain ${PAYARA_DOMAIN}"
    command: sh -c "deploy ${DEPLOYMENTS_DIR}${WAR_FILE}"
    build: payara
    ports:
      - 4848:4848
      - 8080:8080
      - 8181:8181
    volumes:
      - ./logs:/opt/payara/appserver/glassfish/domains/payaradomain/logs
      - ./build/libs:/opt/payara/deployments
    working_dir: /opt/payara/deployments
    environment:
      - USER=admin
      - PAYARA_DOMAIN=payaradomain
      - DEPLOYMENTS_DIR=/opt/payara/deployments
      - WAR_FILE=/twitter.war
      - AS_ADMIN_PATH=/opt/payara/appserver/bin/asadmin
      - PASSWORDFILE_PATH=/opt/payara/passwordFile

